version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: dive_app_db
    environment:
      POSTGRES_USER: diveapp
      POSTGRES_PASSWORD: diveapp123
      POSTGRES_DB: diveapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:7-alpine
    container_name: dive_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: